import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service – GossipAI",
  description: "The terms and conditions governing your use of GossipAI.",
};

const LAST_UPDATED = "March 28, 2026";
const CONTACT_EMAIL = "support@gossip-ai.site";
const APP_NAME = "GossipAI";
const COMPANY = "GossipAI";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f5f0ff] text-[#1a0a2e]">
      {/* Navbar */}
      <nav className="mx-auto flex w-full max-w-3xl items-center justify-between px-6 py-5">
        <Link href="/" className="flex items-center gap-2.5">
          <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#7f19e6] text-[11px] font-bold text-white">
            GA
          </div>
          <span className="text-sm font-semibold">GossipAI</span>
        </Link>
        <Link href="/" className="text-sm text-[#7a5e96] hover:text-[#7f19e6] hover:underline">
          ← Back to home
        </Link>
      </nav>

      {/* Content */}
      <main className="mx-auto w-full max-w-3xl px-6 pb-20">
        <h1 className="mb-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Terms of Service</h1>
        <p className="mb-10 text-sm text-[#7a5e96]">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-8">

          <Section title="1. Acceptance of Terms">
            <p>
              By downloading, installing, or using the {APP_NAME} mobile application or web service (the &quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service. These Terms form a binding agreement between you and {COMPANY}.
            </p>
          </Section>

          <Section title="2. Eligibility">
            <p>
              You must be at least 13 years of age (or 16 in the EU) to use the Service. By using the Service, you represent that you meet this requirement. If you are under 18, you confirm that you have obtained parental or guardian consent.
            </p>
          </Section>

          <Section title="3. Description of Service">
            <p>
              {APP_NAME} is an AI-powered relationship communication assistant. The Service provides suggestions, analyses, and summaries to help you compose messages and navigate interpersonal situations. The Service is for informational and personal communication assistance purposes only.
            </p>
            <p>
              <strong>The Service does not provide professional mental health, legal, or medical advice.</strong> If you are in crisis or need professional support, please contact a qualified professional or emergency services.
            </p>
          </Section>

          <Section title="4. User Accounts">
            <ul>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You agree to provide accurate and up-to-date information during registration.</li>
              <li>You must notify us immediately of any unauthorised use of your account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
            </ul>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Harass, threaten, or harm any person.</li>
              <li>Generate content that is unlawful, defamatory, fraudulent, or violates any third party&apos;s rights.</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service.</li>
              <li>Circumvent any rate limits, security controls, or access restrictions.</li>
              <li>Use the Service in any way that violates applicable local, national, or international law.</li>
            </ul>
          </Section>

          <Section title="6. AI-Generated Content Disclaimer">
            <p>
              Responses generated by the Service are produced by AI models and are provided &quot;as is&quot; for informational purposes only. {COMPANY} does not guarantee the accuracy, completeness, or suitability of AI-generated content for any particular purpose. You are solely responsible for any decisions or actions you take based on content from the Service.
            </p>
          </Section>

          <Section title="7. Intellectual Property">
            <p>
              The Service and its original content (excluding user-submitted content) are and will remain the exclusive property of {COMPANY}. You are granted a limited, non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes in accordance with these Terms.
            </p>
            <p>
              You retain ownership of content you submit to the Service. By submitting content, you grant {COMPANY} a limited licence to process it solely to provide the Service.
            </p>
          </Section>

          <Section title="8. Privacy">
            <p>
              Your use of the Service is also governed by our{" "}
              <Link href="/privacy" className="text-[#7f19e6] hover:underline">Privacy Policy</Link>
              , which is incorporated into these Terms by reference.
            </p>
          </Section>

          <Section title="9. Payments & Subscriptions">
            <p>
              Certain features of the Service may require a paid subscription or in-app purchase. All payments are processed through Apple App Store, Google Play, or Stripe. Subscription prices and terms are displayed at the point of purchase. Refunds are subject to the applicable platform&apos;s refund policy.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We may suspend or terminate your access to the Service at any time, with or without notice, for conduct that we determine violates these Terms or is harmful to other users, us, or third parties. You may terminate your account at any time by contacting us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#7f19e6] hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </Section>

          <Section title="11. Disclaimer of Warranties">
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.
            </p>
          </Section>

          <Section title="12. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {COMPANY.toUpperCase()} SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM RELATING TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
            </p>
          </Section>

          <Section title="13. Governing Law">
            <p>
              These Terms are governed by and construed in accordance with the laws of the European Union and the jurisdiction in which {COMPANY} operates, without regard to conflict of law principles.
            </p>
          </Section>

          <Section title="14. Changes to These Terms">
            <p>
              We reserve the right to modify these Terms at any time. We will notify you of material changes by updating the &quot;Last updated&quot; date. Continued use of the Service after such changes constitutes your acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="15. Contact Us">
            <p>
              For questions about these Terms, please contact us at:{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#7f19e6] hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </Section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#7f19e6]/10 py-8">
        <div className="mx-auto flex w-full max-w-3xl flex-wrap items-center justify-between gap-4 px-6">
          <p className="text-xs text-[#7a5e96]">© {new Date().getFullYear()} GossipAI. All rights reserved.</p>
          <div className="flex gap-5 text-xs text-[#7a5e96]">
            <Link href="/privacy" className="hover:text-[#7f19e6] hover:underline">Privacy Policy</Link>
            <Link href="/terms" className="font-medium text-[#7f19e6]">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="mb-3 text-lg font-bold">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-[#3d2060]">{children}</div>
    </div>
  );
}
