"use client";

import Link from "next/link";
import { LegalSection, LegalShell } from "@/components/app/legal/legal-shell";
import {
  LEGAL_APP_NAME,
  LEGAL_COMPANY,
  LEGAL_CONTACT_EMAIL,
} from "@/components/app/legal/legal-config";

const LAST_UPDATED = "May 6, 2026";

export function TermsPageClient() {
  return (
    <LegalShell title="Terms of Service" subtitle={`Last updated: ${LAST_UPDATED}`} active="terms">
      <LegalSection title="1. Acceptance of Terms">
        <p>
          By downloading, installing, or using the {LEGAL_APP_NAME} mobile application or web service (the &quot;Service&quot;),
          you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service.
          These Terms form a binding agreement between you and {LEGAL_COMPANY}.
        </p>
      </LegalSection>

      <LegalSection title="2. Eligibility">
        <p>
          The Service is intended for adults. You must be at least 18 years old to create an account or use GossipAI.
          By using the Service, you represent and warrant that you meet this age requirement.
        </p>
      </LegalSection>

      <LegalSection title="3. Description of Service">
        <p>
          {LEGAL_APP_NAME} is an AI-powered relationship communication assistant. The Service provides suggestions,
          analyses, and summaries to help you compose messages and navigate interpersonal situations.
        </p>
        <p>
          <strong className="text-(--dt-on-surface)">The Service does not provide professional mental health, legal, or medical advice.</strong>
        </p>
      </LegalSection>

      <LegalSection title="4. User Accounts">
        <ul className="list-disc space-y-2 pl-5">
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You agree to provide accurate and up-to-date information during registration.</li>
          <li>You must notify us immediately of any unauthorised use of your account.</li>
          <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Acceptable Use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Harass, threaten, or harm any person.</li>
          <li>Generate unlawful, defamatory, fraudulent, or rights-violating content.</li>
          <li>Submit abusive, hateful, exploitative, or community-standards-violating material.</li>
          <li>Attempt to reverse-engineer, scrape, or extract data from the Service.</li>
          <li>Circumvent rate limits, security controls, or access restrictions.</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. AI-Generated Content Disclaimer">
        <p>
          Responses generated by the Service are produced by AI models and are provided &quot;as is&quot; for informational
          purposes only. You are solely responsible for any decisions or actions based on this output.
        </p>
      </LegalSection>

      <LegalSection title="7. Intellectual Property">
        <p>
          The Service and its original content (excluding user-submitted content) are and will remain the exclusive
          property of {LEGAL_COMPANY}. You are granted a limited, non-exclusive, non-transferable licence to use the Service.
        </p>
      </LegalSection>

      <LegalSection title="8. Privacy">
        <p>
          Your use of the Service is also governed by our <Link href="/privacy" className="text-(--dt-primary) hover:underline">Privacy Policy</Link>.
        </p>
      </LegalSection>

      <LegalSection title="9. Payments & Subscriptions">
        <p>
          Certain features may require paid subscriptions or in-app purchases. Subscription status and receipt handling
          may be managed through RevenueCat, while billing is processed by Apple App Store or Google Play according to
          their platform terms. Please review our{" "}
          <Link href="/refund" className="text-(--dt-primary) hover:underline">
            Refund Policy
          </Link>{" "}
          for purchase, cancellation, and support details.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p>
          We may suspend or terminate your access at any time for Terms violations. Contact: <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-(--dt-primary) hover:underline">{LEGAL_CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>

      <LegalSection title="11. Disclaimer of Warranties">
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND.
        </p>
      </LegalSection>

      <LegalSection title="12. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, {LEGAL_COMPANY.toUpperCase()} SHALL NOT BE LIABLE FOR INDIRECT,
          INCIDENTAL, OR CONSEQUENTIAL DAMAGES.
        </p>
      </LegalSection>

      <LegalSection title="13. Governing Law">
        <p>
          These Terms are governed by applicable European Union and local laws where {LEGAL_COMPANY} operates.
        </p>
      </LegalSection>

      <LegalSection title="14. Changes to These Terms">
        <p>
          We may update these Terms or the Service from time to time. When changes are material, we may provide notice
          through the app, website, or other reasonable means. Continued usage after the effective date means
          acceptance.
        </p>
      </LegalSection>

      <LegalSection title="15. Contact Us">
        <p>
          For questions about these Terms, contact <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-(--dt-primary) hover:underline">{LEGAL_CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
